port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254

proxies:
  - name: (ID) Amazon.com, Inc ğŸ‡®ğŸ‡©
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 14814b9d-11df-411c-b023-99198d0d4cc1
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /id-amz
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true

  - name: (ID) RumahWeb ğŸ‡®ğŸ‡©
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: f60e55d2-57e0-40e8-8146-56eeff893719
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /id-rweb
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true

  - name: (SG) Tencent ğŸ‡¸ğŸ‡¬
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 78bd974c-31af-45ed-b9e0-f2d8b5ffd680
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.vip-12.indoxray.top
    network: ws
    ws-opts:
      path: /websocket-vless
      headers:
        Host: ava.game.naver.com.vip-12.indoxray.top
    udp: true

  - name: (SG) OVH SAS ğŸ‡¸ğŸ‡¬
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 440c8794-9fb1-4498-b56c-fa6d25dd7652
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /sg-ovh
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true

proxy-groups:
  - name: SERVER ID ğŸ‡®ğŸ‡©
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 120
    strategy: round-robin
    proxies:
      - (ID) Amazon.com, Inc ğŸ‡®ğŸ‡©
      - (ID) RumahWeb ğŸ‡®ğŸ‡©
  
  - name: SERVER SG ğŸ‡¸ğŸ‡¬
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 90
    proxies:
      - (SG) Tencent ğŸ‡¸ğŸ‡¬
      - (SG) OVH SAS ğŸ‡¸ğŸ‡¬
      
  - name: IKLAN â›”
    type: select
    proxies:
     - SERVER SG ğŸ‡¸ğŸ‡¬
     - REJECT

  - name: GAME ğŸ²
    type: select
    proxies:
     - SERVER ID ğŸ‡®ğŸ‡©
     - DIRECT
     - REJECT

  - name: SOSMED ğŸŒ
    type: select
    proxies:
     - SERVER SG ğŸ‡¸ğŸ‡¬
     - DIRECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN â›”
 - RULE-SET,Game,GAME ğŸ²
 - RULE-SET,Sosmed,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,Indo,SERVER ID ğŸ‡®ğŸ‡©
 - RULE-SET,Umum,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,Streaming,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,Banking,SERVER ID ğŸ‡®ğŸ‡©
 - RULE-SET,Tiktok,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,Meta,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,PortGame,GAME ğŸ²
 - MATCH,SERVER SG ğŸ‡¸ğŸ‡¬


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  Indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Banking:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml
