port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
ip-version: 4
mode: rule
log-level: info
allow-lan: true
external-controller: 127.0.0.1:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.mcdn.bilivideo.cn"
    - +.media.dssott.com
  use-hosts: true
  listen: 127.0.0.1:7874
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - https://dns.alidns.com/dns-query
    - 112.215.203.254
  fallback:
    - 1.0.0.1
    - 8.8.4.4
    - https://dns.alidns.com/dns-query
    - 114.114.114.114
    - tls://dns.google
    - tls://1.1.1.1
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254

proxies:
  - name: (ID) Amazon.com, Inc ğŸ‡®ğŸ‡©
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 51604dea-5450-4926-96de-1dee9dbcc6ad
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: graph.instagram.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /id-amz
      headers:
        Host: graph.instagram.com.violetvpn.biz.id
    udp: true

  - name: (ID) RumahWeb ğŸ‡®ğŸ‡©
    server: df.game.naver.com
    port: 443
    type: vless
    uuid: 16ca11e1-fc61-4b8d-8760-a6a9717f6cd1
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: violetvpn.biz.id
    network: ws
    ws-opts:
      path: /id-rweb
      headers:
        Host: violetvpn.biz.id
    udp: true

  - name: (SG) Tencent ğŸ‡¸ğŸ‡¬
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 78bd974c-31af-45ed-b9e0-f2d8b5ffd680
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.vip-12.indoxray.top
    network: ws
    ws-opts:
      path: /websocket-vless
      headers:
        Host: ava.game.naver.com.vip-12.indoxray.top
    udp: true

  - name: (SG) OVH SAS ğŸ‡¸ğŸ‡¬
    server: ava.game.naver.com
    port: 443
    type: vless
    uuid: 440c8794-9fb1-4498-b56c-fa6d25dd7652
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.violetvpn.biz.id
    network: ws
    ws-opts:
      path: /sg-ovh
      headers:
        Host: ava.game.naver.com.violetvpn.biz.id
    udp: true

proxy-groups:
  - name: SERVER ID ğŸ‡®ğŸ‡©
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 180
    udp: true
    proxies:
      - (ID) Amazon.com, Inc ğŸ‡®ğŸ‡©
      - (ID) RumahWeb ğŸ‡®ğŸ‡©
  
  - name: SERVER SG ğŸ‡¸ğŸ‡¬
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 180
    udp: true
    proxies:
      - (SG) Tencent ğŸ‡¸ğŸ‡¬
      - (SG) OVH SAS ğŸ‡¸ğŸ‡¬

  - name: SOSMED ğŸŒ
    type: select
    proxies:
     - SERVER SG ğŸ‡¸ğŸ‡¬
     - DIRECT
      
  - name: IKLAN â›”
    type: select
    proxies:
     - SERVER SG ğŸ‡¸ğŸ‡¬
     - REJECT

  - name: GAME ğŸ²
    type: select
    proxies:
     - SERVER ID ğŸ‡®ğŸ‡©
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Sosmed,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,Block,IKLAN â›”
 - RULE-SET,Game,GAME ğŸ²
 - RULE-SET,Indo,SERVER ID ğŸ‡®ğŸ‡©
 - RULE-SET,Umum,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,Streaming,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,Banking,SERVER ID ğŸ‡®ğŸ‡©
 - RULE-SET,Tiktok,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,Meta,SERVER SG ğŸ‡¸ğŸ‡¬
 - RULE-SET,PortGame,GAME ğŸ²
 - MATCH,SERVER SG ğŸ‡¸ğŸ‡¬


rule-providers:
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  Indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Banking:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml
